<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "upload_example"
 *
 * Auto generated by Extension Builder 19-02-14
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = [
    'title' => 'Example Extension',
    'description' => 'Just examples for a Blog Post',
    'category' => 'Example Extensions',
    'author' => 'Helmut Hummel',
    'author_email' => '',
    'author_company' => '',
    'shy' => '',
    'priority' => '',
    'module' => '',
    'state' => 'alpha',
    'internal' => '',
    'uploadfolder' => '0',
    'createDirs' => '',
    'modify_tables' => '',
    'clearCacheOnLoad' => 0,
    'lockType' => '',
    'version' => '0.0.2',
    'constraints' => [
        'depends' => [
            'typo3' => '6.2.4-8.4.99',
            'php' => '5.5.0-',
        ],
        'conflicts' => [
        ],
        'suggests' => [
        ],
    ],
];
