<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "upload_example"
 *
 * Auto generated by Extension Builder 19-02-14
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = array(
	'title' => 'Example Extension',
	'description' => 'Just examples for a Blog Post',
	'category' => 'Example Extensions',
	'author' => 'Helmut Hummel',
	'author_email' => '',
	'author_company' => '',
	'shy' => '',
	'priority' => '',
	'module' => '',
	'state' => 'alpha',
	'internal' => '',
	'uploadfolder' => '0',
	'createDirs' => '',
	'modify_tables' => '',
	'clearCacheOnLoad' => 0,
	'lockType' => '',
	'version' => '0.0.1',
	'constraints' => array(
		'depends' => array(
			'extbase' => '6.2',
			'fluid' => '6.2',
			'typo3' => '6.2',
			'news' => '',
		),
		'conflicts' => array(
		),
		'suggests' => array(
		),
	),
);

?>